name: katallaxie

nextApp:
  component: "@sls-next/serverless-component@1.19.0-alpha.40"
  inputs:
    memory: 1024
    domain: ["katallaxie.me"]
    cloudfront:
      aliases: ["katallaxie.dev", "www.katallaxie.dev", "pixelmilk.com", "www.pixelmilk.com", "pixelmilk.de", "www.pixelmilk.de"]
      certificate:
        cloudFrontDefaultCertificate: false
        acmCertificateArn: "arn:aws:acm:us-east-1:812538918571:certificate/dbc8c3d6-c905-4ab6-bc1b-114e6f1515c8"
